services:
  web:
    build: '.'
    ports:
      - '80:3000'
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file: 'docker.env'
    restart: unless-stopped
  migrate:
    build: '.'
    command: bun db:push
    env_file: 'docker.env'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: slickage-website
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
