name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format check
        run: bun run format

      - name: Lint
        run: bun run lint

      - name: Type Check
        run: bun run tsc --noEmit

      - name: Test
        run: echo "No tests yet"
