name: CI

on:
  pull_request:
    branches: [main, prod]

# Add concurrency to cancel outdated runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format check
        run: bun run format:check

      - name: Lint
        run: bun run lint

      - name: Type Check
        run: bun run tsc:check

  test:
    name: Test Suite
    needs: code-quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test-suite: integration
            test-command: 'bun test tests/integration/'
            test-name: 'Integration Tests'
            redis-port: 6380
          - test-suite: core
            test-command: 'bun test tests/core/'
            test-name: 'Core Tests'
      fail-fast: true

    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
        ports:
          - ${{ matrix.redis-port }}:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ${{ matrix.test-name }}
        run: ${{ matrix.test-command }}
        env:
          NODE_ENV: test
          REDIS_URL: redis://localhost:${{ matrix.redis-port }}
