name: Build and Push Docker image to ECR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format code
        run: bun run format

      - name: Lint
        run: bun run lint

      - name: Type Check
        run: bun run tsc --noEmit

      - name: Test (placeholder)
        run: echo "No tests yet"

      - name: Build project
        run: bun run build
        if: github.event_name == 'push'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        if: github.event_name == 'push'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        if: github.event_name == 'push'

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .
        if: github.event_name == 'push'

      - name: Tag Docker image to latest
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} ${{ secrets.ECR_REPOSITORY }}:latest
        if: github.event_name == 'push'

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
        if: github.event_name == 'push'

      - name: Push latest Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
        if: github.event_name == 'push'
